---
kind: pipeline
name: test_and_build
services:
  - image: docker:dind
    name: dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run
steps:
  - commands:
      - git fetch --tags
    image: alpine/git
    name: fetch
  - commands:
      - sleep 10
      - ls -l /var/run/docker.sock
      - test -S /var/run/docker.sock && echo 'Docker socket found' || echo 'Docker socket
        missing'
    image: alpine
    name: debug_dind
    volumes:
      - name: dockersock
        path: /var/run
  - commands:
      - ./scripts/go-test.sh
    environment:
      GOPROXY: http://goproxy
    image: publicawesome/golang:1.23.8-devtooling
    name: test
  - commands:
      - apk add --no-cache ca-certificates build-base git
      - wget https://github.com/CosmWasm/wasmvm/releases/download/v2.2.3/libwasmvm_muslc.x86_64.a
        -O /lib/libwasmvm_muslc.x86_64.a
      - echo '32503fe35a7be202c5f7c3051497d6e4b3cd83079a61f5a0bf72a2a455b6d820 /lib/libwasmvm_muslc.x86_64.a'
        | sha256sum -c
      - LEDGER_ENABLED=false BUILD_TAGS=muslc LINK_STATICALLY=true  make build
      - echo 'Ensuring binary is statically linked ...' && (file $PWD/bin/starsd | grep
        'statically linked')
    environment:
      GOPROXY: http://goproxy
    image: golang:1.23.8-alpine3.20
    name: build
  - commands:
      - docker build -t publicawesome/stargaze:latest .
    image: docker:24
    name: build_docker
    volumes:
      - name: dockersock
        path: /var/run
type: docker
volumes:
  - name: dockersock
    temp: {}
